package entities;

public class Pays {
    public final String code;
    public final String nom;
    public final String indicatif;

    public Pays(String code, String nom, String indicatif) {
        this.code = code;
        this.nom = nom;
        this.indicatif = indicatif;
    }

    @Override
    public String toString() {
        return "+" + indicatif + "  " + nom;
    }

    public static java.util.List<Pays> listeComplete() {
        java.util.List<Pays> liste = new java.util.ArrayList<>();
        liste.add(new Pays("af", "Afghanistan", "93"));
        liste.add(new Pays("za", "Afrique du Sud", "27"));
        liste.add(new Pays("ax", "Åland", "358"));
        liste.add(new Pays("al", "Albanie", "355"));
        liste.add(new Pays("dz", "Algérie", "213"));
        liste.add(new Pays("de", "Allemagne", "49"));
        liste.add(new Pays("ad", "Andorre", "376"));
        liste.add(new Pays("ao", "Angola", "244"));
        liste.add(new Pays("ai", "Anguilla", "1"));
        liste.add(new Pays("aq", "Antarctique", "672"));
        liste.add(new Pays("ag", "Antigua-et-Barbuda", "1"));
        liste.add(new Pays("sa", "Arabie Saoudite", "966"));
        liste.add(new Pays("ar", "Argentine", "54"));
        liste.add(new Pays("am", "Arménie", "374"));
        liste.add(new Pays("aw", "Aruba", "297"));
        liste.add(new Pays("au", "Australie", "61"));
        liste.add(new Pays("at", "Autriche", "43"));
        liste.add(new Pays("az", "Azerbaïdjan", "994"));
        liste.add(new Pays("bs", "Bahamas", "1"));
        liste.add(new Pays("bh", "Bahreïn", "973"));
        liste.add(new Pays("bd", "Bangladesh", "880"));
        liste.add(new Pays("be", "Belgique", "32"));
        liste.add(new Pays("bz", "Belize", "501"));
        liste.add(new Pays("bj", "Bénin", "229"));
        liste.add(new Pays("bm", "Bermudes", "1"));
        liste.add(new Pays("bt", "Bhoutan", "975"));
        liste.add(new Pays("by", "Biélorussie", "375"));
        liste.add(new Pays("bo", "Bolivie", "591"));
        liste.add(new Pays("bq", "Bonaire, Saint-Eustache et Saba", "599"));
        liste.add(new Pays("ba", "Bosnie-Herzégovine", "387"));
        liste.add(new Pays("bw", "Botswana", "267"));
        liste.add(new Pays("br", "Brésil", "55"));
        liste.add(new Pays("bn", "Brunei Darussalam", "673"));
        liste.add(new Pays("bg", "Bulgarie", "359"));
        liste.add(new Pays("bf", "Burkina Faso", "226"));
        liste.add(new Pays("bi", "Burundi", "257"));
        liste.add(new Pays("kh", "Cambodge", "855"));
        liste.add(new Pays("cm", "Cameroun", "237"));
        liste.add(new Pays("ca", "Canada", "1"));
        liste.add(new Pays("cv", "Cap-Vert", "238"));
        liste.add(new Pays("cl", "Chili", "56"));
        liste.add(new Pays("cn", "Chine", "86"));
        liste.add(new Pays("cy", "Chypre", "357"));
        liste.add(new Pays("co", "Colombie", "57"));
        liste.add(new Pays("km", "Comores", "269"));
        liste.add(new Pays("kp", "Corée du Nord", "850"));
        liste.add(new Pays("kr", "Corée du Sud", "82"));
        liste.add(new Pays("cr", "Costa Rica", "506"));
        liste.add(new Pays("ci", "Côte-d'Ivoire", "225"));
        liste.add(new Pays("hr", "Croatie", "385"));
        liste.add(new Pays("cu", "Cuba", "53"));
        liste.add(new Pays("cw", "Curaçao", "599"));
        liste.add(new Pays("dk", "Danemark", "45"));
        liste.add(new Pays("dj", "Djibouti", "253"));
        liste.add(new Pays("dm", "Dominique", "1"));
        liste.add(new Pays("eg", "Égypte", "20"));
        liste.add(new Pays("sv", "El Salvador", "503"));
        liste.add(new Pays("ae", "Émirats Arabes Unis", "971"));
        liste.add(new Pays("ec", "Équateur", "593"));
        liste.add(new Pays("er", "Érythrée", "291"));
        liste.add(new Pays("es", "Espagne", "34"));
        liste.add(new Pays("ee", "Estonie", "372"));
        liste.add(new Pays("us", "États-Unis d'Amérique", "1"));
        liste.add(new Pays("et", "Éthiopie", "251"));
        liste.add(new Pays("fj", "Fidji", "679"));
        liste.add(new Pays("fi", "Finlande", "358"));
        liste.add(new Pays("fr", "France", "33"));
        liste.add(new Pays("ga", "Gabon", "241"));
        liste.add(new Pays("gm", "Gambie", "220"));
        liste.add(new Pays("ge", "Géorgie", "995"));
        liste.add(new Pays("gs", "Géorgie du Sud-et-les Îles Sandwich du Sud", "500"));
        liste.add(new Pays("gh", "Ghana", "233"));
        liste.add(new Pays("gi", "Gibraltar", "350"));
        liste.add(new Pays("gr", "Grèce", "30"));
        liste.add(new Pays("gd", "Grenade", "1"));
        liste.add(new Pays("gl", "Groenland", "299"));
        liste.add(new Pays("gp", "Guadeloupe", "590"));
        liste.add(new Pays("gt", "Guatemala", "502"));
        liste.add(new Pays("gg", "Guernesey", "44"));
        liste.add(new Pays("gn", "Guinée", "224"));
        liste.add(new Pays("gq", "Guinée équatoriale", "240"));
        liste.add(new Pays("gw", "Guinée-Bissau", "245"));
        liste.add(new Pays("gy", "Guyana", "592"));
        liste.add(new Pays("gf", "Guyane française", "594"));
        liste.add(new Pays("ht", "Haïti", "509"));
        liste.add(new Pays("hn", "Honduras", "504"));
        liste.add(new Pays("hk", "Hong Kong", "852"));
        liste.add(new Pays("hu", "Hongrie", "36"));
        liste.add(new Pays("bv", "Île Bouvet", "47"));
        liste.add(new Pays("cx", "Île Christmas", "61"));
        liste.add(new Pays("im", "Île de Man", "44"));
        liste.add(new Pays("nf", "Île Norfolk", "672"));
        liste.add(new Pays("ky", "Îles Caïmans", "1"));
        liste.add(new Pays("cc", "Îles Cocos", "61"));
        liste.add(new Pays("ck", "Îles Cook", "682"));
        liste.add(new Pays("fo", "Îles Féroé", "298"));
        liste.add(new Pays("hm", "Îles Heard-et-MacDonald", "672"));
        liste.add(new Pays("fk", "Îles Malouines", "500"));
        liste.add(new Pays("mp", "Îles Mariannes du Nord", "1"));
        liste.add(new Pays("mh", "Îles Marshall", "692"));
        liste.add(new Pays("um", "Îles mineures éloignées des États-Unis", "1"));
        liste.add(new Pays("pn", "Îles Pitcairn", "64"));
        liste.add(new Pays("sb", "Îles Salomon", "677"));
        liste.add(new Pays("tc", "Îles Turques-et-Caïques", "1"));
        liste.add(new Pays("vi", "Îles vierges américaines", "1"));
        liste.add(new Pays("vg", "Îles vierges britanniques", "1"));
        liste.add(new Pays("in", "Inde", "91"));
        liste.add(new Pays("id", "Indonésie", "62"));
        liste.add(new Pays("iq", "Irak", "964"));
        liste.add(new Pays("ir", "Iran", "98"));
        liste.add(new Pays("ie", "Irlande", "353"));
        liste.add(new Pays("is", "Islande", "354"));
        liste.add(new Pays("il", "Israël", "972"));
        liste.add(new Pays("it", "Italie", "39"));
        liste.add(new Pays("jm", "Jamaïque", "1"));
        liste.add(new Pays("jp", "Japon", "81"));
        liste.add(new Pays("je", "Jersey", "44"));
        liste.add(new Pays("jo", "Jordanie", "962"));
        liste.add(new Pays("kz", "Kazakhstan", "7"));
        liste.add(new Pays("ke", "Kenya", "254"));
        liste.add(new Pays("kg", "Kirghizistan", "996"));
        liste.add(new Pays("ki", "Kiribati", "686"));
        liste.add(new Pays("xk", "Kosovo", "383"));
        liste.add(new Pays("kw", "Koweït", "965"));
        liste.add(new Pays("la", "Laos", "856"));
        liste.add(new Pays("ls", "Lesotho", "266"));
        liste.add(new Pays("lv", "Lettonie", "371"));
        liste.add(new Pays("lb", "Liban", "961"));
        liste.add(new Pays("lr", "Libéria", "231"));
        liste.add(new Pays("ly", "Libye", "218"));
        liste.add(new Pays("li", "Liechtenstein", "423"));
        liste.add(new Pays("lt", "Lituanie", "370"));
        liste.add(new Pays("lu", "Luxembourg", "352"));
        liste.add(new Pays("mo", "Macao", "853"));
        liste.add(new Pays("mk", "Macédoine du Nord", "389"));
        liste.add(new Pays("mg", "Madagascar", "261"));
        liste.add(new Pays("my", "Malaisie", "60"));
        liste.add(new Pays("mw", "Malawi", "265"));
        liste.add(new Pays("mv", "Maldives", "960"));
        liste.add(new Pays("ml", "Mali", "223"));
        liste.add(new Pays("mt", "Malte", "356"));
        liste.add(new Pays("ma", "Maroc", "212"));
        liste.add(new Pays("mq", "Martinique", "596"));
        liste.add(new Pays("mu", "Maurice", "230"));
        liste.add(new Pays("mr", "Mauritanie", "222"));
        liste.add(new Pays("yt", "Mayotte", "262"));
        liste.add(new Pays("mx", "Mexique", "52"));
        liste.add(new Pays("fm", "Micronésie", "691"));
        liste.add(new Pays("md", "Moldavie", "373"));
        liste.add(new Pays("mc", "Monaco", "377"));
        liste.add(new Pays("mn", "Mongolie", "976"));
        liste.add(new Pays("me", "Monténégro", "382"));
        liste.add(new Pays("ms", "Montserrat", "1"));
        liste.add(new Pays("mz", "Mozambique", "258"));
        liste.add(new Pays("mm", "Myanmar", "95"));
        liste.add(new Pays("na", "Namibie", "264"));
        liste.add(new Pays("nr", "Nauru", "674"));
        liste.add(new Pays("np", "Népal", "977"));
        liste.add(new Pays("ni", "Nicaragua", "505"));
        liste.add(new Pays("ne", "Niger", "227"));
        liste.add(new Pays("ng", "Nigéria", "234"));
        liste.add(new Pays("nu", "Niué", "683"));
        liste.add(new Pays("no", "Norvège", "47"));
        liste.add(new Pays("nc", "Nouvelle-Calédonie", "687"));
        liste.add(new Pays("nz", "Nouvelle-Zélande", "64"));
        liste.add(new Pays("io", "Océan Indien Britannique", "246"));
        liste.add(new Pays("om", "Oman", "968"));
        liste.add(new Pays("ug", "Ouganda", "256"));
        liste.add(new Pays("uz", "Ouzbékistan", "998"));
        liste.add(new Pays("pk", "Pakistan", "92"));
        liste.add(new Pays("pw", "Palaos", "680"));
        liste.add(new Pays("ps", "Palestine", "970"));
        liste.add(new Pays("pa", "Panama", "507"));
        liste.add(new Pays("pg", "Papouasie-Nouvelle-Guinée", "675"));
        liste.add(new Pays("py", "Paraguay", "595"));
        liste.add(new Pays("nl", "Pays-Bas", "31"));
        liste.add(new Pays("pe", "Pérou", "51"));
        liste.add(new Pays("ph", "Philippines", "63"));
        liste.add(new Pays("pl", "Pologne", "48"));
        liste.add(new Pays("pf", "Polynésie française", "689"));
        liste.add(new Pays("pr", "Porto Rico", "1"));
        liste.add(new Pays("pt", "Portugal", "351"));
        liste.add(new Pays("qa", "Qatar", "974"));
        liste.add(new Pays("cf", "République Centrafricaine", "236"));
        liste.add(new Pays("cd", "République démocratique du Congo", "243"));
        liste.add(new Pays("do", "République Dominicaine", "1"));
        liste.add(new Pays("cg", "République du Congo", "242"));
        liste.add(new Pays("cz", "République Tchèque", "420"));
        liste.add(new Pays("tz", "République unie de Tanzanie", "255"));
        liste.add(new Pays("re", "Réunion", "262"));
        liste.add(new Pays("ro", "Roumanie", "40"));
        liste.add(new Pays("sz", "Royaume d'Eswatini", "268"));
        liste.add(new Pays("gb", "Royaume-Uni", "44"));
        liste.add(new Pays("ru", "Russie", "7"));
        liste.add(new Pays("rw", "Rwanda", "250"));
        liste.add(new Pays("eh", "Sahara occidental", "212"));
        liste.add(new Pays("bl", "Saint-Barthélemy", "590"));
        liste.add(new Pays("kn", "Saint-Christophe-et-Niévès", "1"));
        liste.add(new Pays("sm", "Saint-Marin", "378"));
        liste.add(new Pays("mf", "Saint-Martin (partie française)", "590"));
        liste.add(new Pays("sx", "Saint-Martin (partie néerlandaise)", "1"));
        liste.add(new Pays("pm", "Saint-Pierre-et-Miquelon", "508"));
        liste.add(new Pays("va", "Saint-Siège (Vatican)", "39"));
        liste.add(new Pays("vc", "Saint-Vincent-et-les-Grenadines", "1"));
        liste.add(new Pays("sh", "Sainte-Hélène", "290"));
        liste.add(new Pays("lc", "Sainte-Lucie", "1"));
        liste.add(new Pays("ws", "Samoa", "685"));
        liste.add(new Pays("as", "Samoa américaines", "1"));
        liste.add(new Pays("st", "São Tomé-et-Principe", "239"));
        liste.add(new Pays("sn", "Sénégal", "221"));
        liste.add(new Pays("rs", "Serbie", "381"));
        liste.add(new Pays("sc", "Seychelles", "248"));
        liste.add(new Pays("sl", "Sierra Leone", "232"));
        liste.add(new Pays("sg", "Singapour", "65"));
        liste.add(new Pays("sk", "Slovaquie", "421"));
        liste.add(new Pays("si", "Slovénie", "386"));
        liste.add(new Pays("so", "Somalie", "252"));
        liste.add(new Pays("sd", "Soudan", "249"));
        liste.add(new Pays("ss", "Soudan du Sud", "211"));
        liste.add(new Pays("lk", "Sri Lanka", "94"));
        liste.add(new Pays("se", "Suède", "46"));
        liste.add(new Pays("ch", "Suisse", "41"));
        liste.add(new Pays("sr", "Suriname", "597"));
        liste.add(new Pays("sj", "Svalbard et Île Jan Mayen", "47"));
        liste.add(new Pays("sy", "Syrie", "963"));
        liste.add(new Pays("tj", "Tadjikistan", "992"));
        liste.add(new Pays("tw", "Taïwan", "886"));
        liste.add(new Pays("td", "Tchad", "235"));
        liste.add(new Pays("tf", "Terres australes françaises", "672"));
        liste.add(new Pays("th", "Thaïlande", "66"));
        liste.add(new Pays("tl", "Timor-Leste", "670"));
        liste.add(new Pays("tg", "Togo", "228"));
        liste.add(new Pays("tk", "Tokelau", "690"));
        liste.add(new Pays("to", "Tonga", "676"));
        liste.add(new Pays("tt", "Trinité-et-Tobago", "1"));
        liste.add(new Pays("tn", "Tunisie", "216"));
        liste.add(new Pays("tm", "Turkménistan", "993"));
        liste.add(new Pays("tr", "Turquie", "90"));
        liste.add(new Pays("tv", "Tuvalu", "688"));
        liste.add(new Pays("ua", "Ukraine", "380"));
        liste.add(new Pays("uy", "Uruguay", "598"));
        liste.add(new Pays("vu", "Vanuatu", "678"));
        liste.add(new Pays("ve", "Venezuela", "58"));
        liste.add(new Pays("vn", "Vietnam", "84"));
        liste.add(new Pays("wf", "Wallis-et-Futuna", "681"));
        liste.add(new Pays("ye", "Yémen", "967"));
        liste.add(new Pays("zm", "Zambie", "260"));
        liste.add(new Pays("zw", "Zimbabwe", "263"));
        return liste;
    }
}
