/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import controllers.PatientJpaController;
import entities.Patient;
import java.awt.event.ActionEvent;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.sql.SQLException;
/**
 *
 * @author Idayath
 */
public class GESTIONDESPATIENTSJFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GESTIONDESPATIENTSJFrame.class.getName());

    /**
     * Creates new form GESTIONDESPATIENTSJFrame
     */
    public GESTIONDESPATIENTSJFrame() {
        initComponents();
        chargerPatient();
       
    }
     private void chargerPatient() {
    try {
        PatientJpaController controller = new PatientJpaController();
        List<Patient> liste = controller.listerTous();

        DefaultTableModel model = (DefaultTableModel) tablePatient.getModel();
        model.setRowCount(0);

        for (Patient p : liste) {
            model.addRow(new Object[]{
                p.getIdPatient(),
                p.getNomPatient(),
                p.getPrenomPatient(),
                p.getAge(),
                p.getTelephone(),
                p.getEmailPatient()
            });
        }

        System.out.println("Patients chargés : " + liste.size());

    } catch (Exception e) {
        System.out.println("ERREUR : " + e.getMessage());
        e.printStackTrace();
    }
}
    
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePatient = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtIdPatient = new javax.swing.JTextField();
        txtNomPatient = new javax.swing.JTextField();
        txtPrenomPatient = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtTelephone = new javax.swing.JTextField();
        txtEmailPatient = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(55, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("GESTION DES PATIENTS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(245, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(197, 197, 197))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tablePatient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "IdPatient", "NomPatient", "PrenomPatient", "Age", "Telephone", "EmailPatient"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablePatient);
        if (tablePatient.getColumnModel().getColumnCount() > 0) {
            tablePatient.getColumnModel().getColumn(0).setResizable(false);
            tablePatient.getColumnModel().getColumn(1).setResizable(false);
            tablePatient.getColumnModel().getColumn(2).setResizable(false);
            tablePatient.getColumnModel().getColumn(3).setResizable(false);
            tablePatient.getColumnModel().getColumn(4).setResizable(false);
            tablePatient.getColumnModel().getColumn(5).setResizable(false);
        }

        jPanel2.setBackground(new java.awt.Color(55, 204, 255));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Ajouter");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("Enregistrer");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setText("Modifier");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setText("Supprimer");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setText("Fermer");
        jButton5.addActionListener(this::jButton5ActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jButton1)
                .addGap(87, 87, 87)
                .addComponent(jButton2)
                .addGap(82, 82, 82)
                .addComponent(jButton3)
                .addGap(78, 78, 78)
                .addComponent(jButton4)
                .addGap(50, 50, 50)
                .addComponent(jButton5)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addContainerGap())
        );

        jLabel3.setText("IdPatient");

        jLabel4.setText("NomPatient");

        jLabel5.setText("PrenomPatient");

        jLabel6.setText("Age");

        jLabel7.setText("Telephone");

        jLabel8.setText("EmailPatient");

        txtPrenomPatient.addActionListener(this::txtPrenomPatientActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 786, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtIdPatient)
                                    .addComponent(txtNomPatient)
                                    .addComponent(txtPrenomPatient, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE))
                                .addGap(69, 69, 69)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtEmailPatient, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                                    .addComponent(txtTelephone)
                                    .addComponent(txtAge))))
                        .addContainerGap(77, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(txtIdPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(txtNomPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(txtPrenomPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmailPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
     
        txtIdPatient.setText("");
        txtNomPatient.setText("");
        txtPrenomPatient.setText("");
        txtAge.setText("");
        txtTelephone.setText("");
        txtEmailPatient.setText("");
        txtIdPatient.requestFocus();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void viderChamps() {
       
    }

    private void jButton2ActionPerformed(ActionEvent e) {
       
    }
     public class GestionPatientFrame extends JFrame {
            private JTextField txtIdPatient     = new JTextField();
            private JTextField txtNomPatient    = new JTextField();
            private JTextField txtPrenomPatient = new JTextField();
            private JTextField txtAge           = new JTextField();
            private JTextField txtTelephone     = new JTextField();
            private JTextField txtEmailPatient         = new JTextField();
            
             private DefaultTableModel tableModel;
             private JTable table;
             private final PatientJpaController dao = new PatientJpaController();
             
                 private void viderChamps() {
                      txtIdPatient.setText("");
                      txtNomPatient.setText("");
                      txtPrenomPatient.setText("");
                      txtAge.setText("");
                      txtTelephone.setText("");
                      txtEmailPatient.setText("");
                      tablePatient.clearSelection();
}

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        actionEnregistrer();
         new GestionPatientFrame().setVisible(true);            
}
        private void actionEnregistrer() { 
    if (txtNomPatient.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, 
            "Le nom du patient est obligatoire.", 
            "Erreur", JOptionPane.ERROR_MESSAGE);
        txtNomPatient.requestFocus();
        return;
    }
    if (txtPrenomPatient.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, 
            "Le prénom est obligatoire.", 
            "Erreur", JOptionPane.ERROR_MESSAGE);
        txtPrenomPatient.requestFocus();
        return;
    }
    try {
        Patient p = new Patient();
        p.setNomPatient(txtNomPatient.getText().trim());
        p.setPrenomPatient(txtPrenomPatient.getText().trim());
        p.setAge(Integer.parseInt(txtAge.getText().trim()));
        p.setTelephone(txtTelephone.getText().trim());
        p.setEmailPatient(txtEmailPatient.getText().trim());
        PatientJpaController dao = new PatientJpaController();
        if (dao.inserer(p)) {
            JOptionPane.showMessageDialog(this, "Patient enregistré !");
            chargerPatient();
            viderChamps();
        } else {
            JOptionPane.showMessageDialog(this, 
                "Erreur enregistrement.", 
                "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, 
            "L'âge doit être un nombre.", 
            "Erreur", JOptionPane.ERROR_MESSAGE);
    }
} 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
   int ligne = tablePatient.getSelectedRow();
        if (ligne < 0) {
              JOptionPane.showMessageDialog(this, "Sélectionnez un patient.",  "Erreur", JOptionPane.ERROR_MESSAGE);
        return;
}

            String idPatient = tablePatient.getValueAt(ligne, 0).toString();
            PatientJpaController dao = new PatientJpaController();
            Patient p = dao.trouverParId(idPatient);

    if (p == null) {
         JOptionPane.showMessageDialog(this,
             "Patient introuvable.",
             "Erreur", JOptionPane.ERROR_MESSAGE);
    return;
}
p.setNomPatient(txtNomPatient.getText().trim());
p.setPrenomPatient(txtPrenomPatient.getText().trim());
p.setAge(Integer.parseInt(txtAge.getText().trim()));
p.setTelephone(txtTelephone.getText().trim());
p.setEmailPatient(txtEmailPatient.getText().trim());

if (dao.modifier(p)) {
    JOptionPane.showMessageDialog(this, "Patient modifié avec succès !");
    chargerPatient();
    viderChamps();
} else {
    JOptionPane.showMessageDialog(this,
        "Erreur lors de la modification.",
        "Erreur", JOptionPane.ERROR_MESSAGE);
}
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int ligne = tablePatient.getSelectedRow();
if (ligne < 0) {
    JOptionPane.showMessageDialog(this,
        "Sélectionnez un patient à supprimer.",
        "Erreur", JOptionPane.ERROR_MESSAGE);
    return;
}

String idPatient = tablePatient.getValueAt(ligne, 0).toString();
String nom       = tablePatient.getValueAt(ligne, 1).toString();
String prenom    = tablePatient.getValueAt(ligne, 2).toString();

int reponse = JOptionPane.showConfirmDialog(this,
    "Voulez-vous vraiment supprimer :\n\n"
    + prenom + " " + nom + " ?",
    "Confirmation",
    JOptionPane.YES_NO_OPTION,
    JOptionPane.WARNING_MESSAGE);

if (reponse == JOptionPane.YES_OPTION) {
    PatientJpaController dao = new PatientJpaController();
    if (dao.supprimer(idPatient)) {
        JOptionPane.showMessageDialog(this, "Patient supprimé avec succès !");
        chargerPatient();
        viderChamps();
    } else {
        JOptionPane.showMessageDialog(this,
            "Impossible de supprimer ce patient.",
            "Erreur", JOptionPane.ERROR_MESSAGE);
    }
}
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtPrenomPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrenomPatientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrenomPatientActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GESTIONDESPATIENTSJFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablePatient;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtEmailPatient;
    private javax.swing.JTextField txtIdPatient;
    private javax.swing.JTextField txtNomPatient;
    private javax.swing.JTextField txtPrenomPatient;
    private javax.swing.JTextField txtTelephone;
    // End of variables declaration//GEN-END:variables
}



