/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;


import controllers.ConsultationJpaController;
import entities.Consultation;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Idayath
 */
public class GESTIONDESCONSULTATIONSJFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GESTIONDESCONSULTATIONSJFrame.class.getName());

    /**
     * Creates new form GESTIONDESPATIENTS
     */
    public GESTIONDESCONSULTATIONSJFrame() {
        initComponents();
        chargerConsultation();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableConsultation = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnEnregistrer = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtDiagnostic = new javax.swing.JTextField();
        txtMontConsult = new javax.swing.JTextField();
        txtIdConsult = new javax.swing.JTextField();
        txtDateConsult = new javax.swing.JTextField();
        txtMotif = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmbIdPatient = new javax.swing.JComboBox<>();
        cmbIdMedecin = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(55, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("GESTION DE LA CONSULTATION");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(211, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tableConsultation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "IdConsult", "DateConsult", "Motif", "Diagnostic", "MontConsult", "IdPatient", "IdMedecin"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableConsultation);
        if (tableConsultation.getColumnModel().getColumnCount() > 0) {
            tableConsultation.getColumnModel().getColumn(0).setResizable(false);
            tableConsultation.getColumnModel().getColumn(1).setResizable(false);
            tableConsultation.getColumnModel().getColumn(2).setResizable(false);
            tableConsultation.getColumnModel().getColumn(3).setResizable(false);
            tableConsultation.getColumnModel().getColumn(4).setResizable(false);
            tableConsultation.getColumnModel().getColumn(5).setResizable(false);
        }

        jPanel2.setBackground(new java.awt.Color(55, 204, 255));

        btnEnregistrer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEnregistrer.setText("Enregistrer");
        btnEnregistrer.addActionListener(this::btnEnregistrerActionPerformed);

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setText("Modifier");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setText("Supprimer");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setText("Fermer");
        jButton5.addActionListener(this::jButton5ActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(btnEnregistrer)
                .addGap(124, 124, 124)
                .addComponent(jButton3)
                .addGap(102, 102, 102)
                .addComponent(jButton4)
                .addGap(70, 70, 70)
                .addComponent(jButton5)
                .addContainerGap(111, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnregistrer)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addContainerGap())
        );

        jLabel3.setText("IdConsult");

        jLabel4.setText("DateConsult");

        jLabel5.setText("Motif");

        jLabel6.setText("Diagnostic");

        jLabel7.setText("MontConsult");

        jLabel8.setText("IdPatient");

        txtDateConsult.addActionListener(this::txtDateConsultActionPerformed);

        jLabel2.setText("IdMedecin");

        cmbIdPatient.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "P001", "P002", "P003", "P004", "P005", "P006" }));

        cmbIdMedecin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M001", "M002", "M003", "M004", "M005", "M006" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 786, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtIdConsult, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                                    .addComponent(txtDateConsult)
                                                    .addComponent(txtMotif)))
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(58, 58, 58)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(47, 47, 47)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtDiagnostic)
                                            .addComponent(txtMontConsult)
                                            .addComponent(cmbIdPatient, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cmbIdMedecin, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(83, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtIdConsult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtDiagnostic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtDateConsult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtMontConsult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtMotif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(cmbIdPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbIdMedecin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        dispose();
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnEnregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnregistrerActionPerformed
        // TODO add your handling code here:
        if (txtIdConsult.getText().trim().isEmpty()) {
    JOptionPane.showMessageDialog(this, "L'ID est obligatoire.", "Erreur", JOptionPane.ERROR_MESSAGE);
    return;
}
ConsultationJpaController dao = new ConsultationJpaController();
Consultation c = new Consultation();
c.setIdconsult(txtIdConsult.getText().trim());
try {
    c.setDateconsult(new java.util.Date(
        java.sql.Date.valueOf(txtDateConsult.getText().trim()).getTime()
    ));
} catch (IllegalArgumentException e) {
    JOptionPane.showMessageDialog(this,
        "Format date invalide ! Utilisez AAAA-MM-JJ",
        "Erreur", JOptionPane.ERROR_MESSAGE);
    return;
}
c.setMotif(txtMotif.getText().trim());
c.setDiagnostic(txtDiagnostic.getText().trim());
c.setMontconsult(Double.parseDouble(txtMontConsult.getText().trim()));
c.setIdPatient(cmbIdPatient.getSelectedItem().toString().trim());
c.setIdMedecin(cmbIdMedecin.getSelectedItem().toString().trim());
if (dao.inserer(c)) {
    JOptionPane.showMessageDialog(this, "Consultation enregistrée !");
    chargerConsultation();
    viderChamps();
} else {
    JOptionPane.showMessageDialog(this, "Erreur enregistrement.", "Erreur", JOptionPane.ERROR_MESSAGE);
}
        
                
            
        
    
 
    }//GEN-LAST:event_btnEnregistrerActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
      int ligne = tableConsultation.getSelectedRow();
if (ligne < 0) {
    JOptionPane.showMessageDialog(this, "Sélectionnez une consultation.", "Erreur", JOptionPane.ERROR_MESSAGE);
    return;
}
String id = tableConsultation.getValueAt(ligne, 0).toString();
ConsultationJpaController dao = new ConsultationJpaController();
Consultation c = dao.trouverParId(id);
if (c == null) {
    JOptionPane.showMessageDialog(this, "Consultation introuvable.", "Erreur", JOptionPane.ERROR_MESSAGE);
    return;
}
try {
    c.setDateconsult(new java.util.Date(
        java.sql.Date.valueOf(txtDateConsult.getText().trim()).getTime()
    ));
} catch (IllegalArgumentException e) {
    JOptionPane.showMessageDialog(this,
        "Format date invalide ! Utilisez AAAA-MM-JJ",
        "Erreur", JOptionPane.ERROR_MESSAGE);
    return;
}
c.setMotif(txtMotif.getText().trim());
c.setDiagnostic(txtDiagnostic.getText().trim());
c.setMontconsult(Double.parseDouble(txtMontConsult.getText().trim()));
c.setIdPatient(cmbIdPatient.getSelectedItem().toString().trim());
c.setIdMedecin(cmbIdMedecin.getSelectedItem().toString().trim());
if (dao.modifier(c)) {
    JOptionPane.showMessageDialog(this, "Consultation modifiée !");
    chargerConsultation();
    viderChamps();
} else {
    JOptionPane.showMessageDialog(this, "Erreur modification.", "Erreur", JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
       int ligne = tableConsultation.getSelectedRow();
if (ligne < 0) {
    JOptionPane.showMessageDialog(this, "Sélectionnez une consultation.", "Erreur", JOptionPane.ERROR_MESSAGE);
    return;
}
String id = tableConsultation.getValueAt(ligne, 0).toString();
int rep = JOptionPane.showConfirmDialog(this,
    "Supprimer la consultation " + id + " ?",
    "Confirmation", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
if (rep == JOptionPane.YES_OPTION) {
    ConsultationJpaController dao = new ConsultationJpaController();
    if (dao.supprimer(id)) {
        JOptionPane.showMessageDialog(this, "Consultation supprimée !");
        chargerConsultation();
        viderChamps();
    } else {
        JOptionPane.showMessageDialog(this, "Impossible de supprimer.", "Erreur", JOptionPane.ERROR_MESSAGE);
    }
}
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtDateConsultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateConsultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateConsultActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GESTIONDESCONSULTATIONSJFrame().setVisible(true));
    }
    private void chargerConsultation() {
    try {
        ConsultationJpaController dao = new ConsultationJpaController();
        List<Consultation> liste = dao.listerTous();
        DefaultTableModel model = (DefaultTableModel) tableConsultation.getModel();
        model.setRowCount(0);
        for (Consultation c : liste) {
            model.addRow(new Object[]{
                c.getIdconsult(),
                c.getDateconsult(),
                c.getMotif(),
                c.getDiagnostic(),
                c.getMontconsult(),
                c.getIdPatient(),
                c.getIdMedecin()
            });
        }
        System.out.println("Consultations chargées : " + liste.size());
    } catch (Exception e) {
        System.out.println("ERREUR : " + e.getMessage());
    }
}

private void viderChamps() {
    txtIdConsult.setText("");
    txtDateConsult.setText("");
    txtMotif.setText("");
    txtDiagnostic.setText("");
    txtMontConsult.setText("");
    cmbIdPatient.setSelectedIndex(0); 
    cmbIdMedecin.setSelectedIndex(0); 
    tableConsultation.clearSelection();
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnregistrer;
    private javax.swing.JComboBox<String> cmbIdMedecin;
    private javax.swing.JComboBox<String> cmbIdPatient;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableConsultation;
    private javax.swing.JTextField txtDateConsult;
    private javax.swing.JTextField txtDiagnostic;
    private javax.swing.JTextField txtIdConsult;
    private javax.swing.JTextField txtMontConsult;
    private javax.swing.JTextField txtMotif;
    // End of variables declaration//GEN-END:variables
}
