/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;
import javax.swing.JOptionPane;
/**
 *
 * @author Idayath
 */
public class GestionUtilisateursJFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GestionUtilisateursJFrame.class.getName());

    /**
     * Creates new form GestionUtilisateursJFrame
     */
    public GestionUtilisateursJFrame() {
        initComponents();
        chargerUtilisateurs();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableUtilisateurs = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnModifier = new javax.swing.JButton();
        btnSupprimer = new javax.swing.JButton();
        btnFermer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(55, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("GESTION DES UTILISATEURS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(205, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        tableUtilisateurs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "TYPE", "ID", "Nom", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableUtilisateurs);
        if (tableUtilisateurs.getColumnModel().getColumnCount() > 0) {
            tableUtilisateurs.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel2.setBackground(new java.awt.Color(55, 204, 255));

        btnModifier.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnModifier.setText("Modifier");
        btnModifier.addActionListener(this::btnModifierActionPerformed);

        btnSupprimer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSupprimer.setText("Supprimer");
        btnSupprimer.addActionListener(this::btnSupprimerActionPerformed);

        btnFermer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnFermer.setText("Fermer");
        btnFermer.addActionListener(this::btnFermerActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnModifier)
                .addGap(216, 216, 216)
                .addComponent(btnSupprimer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFermer)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModifier)
                    .addComponent(btnSupprimer)
                    .addComponent(btnFermer))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierActionPerformed
        // TODO add your handling code here:
         int ligne = tableUtilisateurs.getSelectedRow();
    if (ligne < 0) {
        JOptionPane.showMessageDialog(this, "Sélectionnez un utilisateur.", "Erreur", JOptionPane.ERROR_MESSAGE);
        return;
    }
    String type = tableUtilisateurs.getValueAt(ligne, 0).toString();
    String id = tableUtilisateurs.getValueAt(ligne, 1).toString();

    if ("Patient".equals(type) || "Médecin".equals(type)) {
        JOptionPane.showMessageDialog(this,
            "Le rôle ne peut être modifié que pour les comptes du personnel (Secrétaire/Caissier/Administrateur).",
            "Non disponible", JOptionPane.INFORMATION_MESSAGE);
        return;
    }

    String[] roles = {"Secrétaire", "Caissier", "Administrateur"};
    String nouveauRole = (String) JOptionPane.showInputDialog(this,
        "Nouveau rôle pour " + id + " :", "Modifier le rôle",
        JOptionPane.QUESTION_MESSAGE, null, roles, type);

    if (nouveauRole != null) {
        boolean succes = new controllers.PersonnelJpaController().modifierRole(id, nouveauRole);
        if (succes) {
            JOptionPane.showMessageDialog(this, "Rôle modifié.");
            chargerUtilisateurs();
        } else {
            JOptionPane.showMessageDialog(this, "Erreur lors de la modification.", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_btnModifierActionPerformed

    private void btnSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimerActionPerformed
        // TODO add your handling code here:
        int ligne = tableUtilisateurs.getSelectedRow();
    if (ligne < 0) {
        JOptionPane.showMessageDialog(this, "Sélectionnez un utilisateur.", "Erreur", JOptionPane.ERROR_MESSAGE);
        return;
    }
    String type = tableUtilisateurs.getValueAt(ligne, 0).toString();
    String id = tableUtilisateurs.getValueAt(ligne, 1).toString();

    int rep = JOptionPane.showConfirmDialog(this,
        "Supprimer le compte " + id + " (" + type + ") ?",
        "Confirmation", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
    if (rep != JOptionPane.YES_OPTION) return;

    boolean succes;
    if ("Patient".equals(type)) {
        succes = new controllers.PatientJpaController().supprimer(id);
    } else if ("Médecin".equals(type)) {
        succes = new controllers.MedecinJpaController().supprimer(id);
    } else {
        succes = new controllers.PersonnelJpaController().supprimer(id);
    }

    if (succes) {
        JOptionPane.showMessageDialog(this, "Compte supprimé.");
        chargerUtilisateurs();
    } else {
        JOptionPane.showMessageDialog(this,
            "Impossible de supprimer : ce compte a probablement des consultations/paiements/factures liés.",
            "Erreur", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnSupprimerActionPerformed

    private void btnFermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFermerActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnFermerActionPerformed

    private void chargerUtilisateurs() {
    javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(
        new String[]{"Type", "ID", "Nom", "Email"}, 0
    );

    for (entities.Patient p : new controllers.PatientJpaController().listerTous()) {
        model.addRow(new Object[]{"Patient", p.getIdPatient(), p.getNomPatient(), p.getEmailPatient()});
    }
    for (entities.Medecin m : new controllers.MedecinJpaController().listerTous()) {
        model.addRow(new Object[]{"Médecin", m.getIdMedecin(), m.getNomMedecin(), m.getEmailMedecin()});
    }
    for (entities.Personnel per : new controllers.PersonnelJpaController().listerTous()) {
        model.addRow(new Object[]{per.getRole(), per.getIdPersonnel(), per.getNomPersonnel(), per.getEmailPersonnel()});
    }

    tableUtilisateurs.setModel(model);
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GestionUtilisateursJFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFermer;
    private javax.swing.JButton btnModifier;
    private javax.swing.JButton btnSupprimer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableUtilisateurs;
    // End of variables declaration//GEN-END:variables
}
