/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import com.itextpdf.text.*;
import com.itextpdf.text.pdf.*;
import java.io.*;
import java.awt.Desktop;
import java.awt.print.PrinterJob;
import javax.swing.JOptionPane;
/**
 *
 * @author Idayath
 */
public class ImprimerJFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ImprimerJFrame.class.getName());

    /**
     * Creates new form ImprimerJFrame
     */
    public ImprimerJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtIdPatient = new javax.swing.JTextField();
        txtDateFacture = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cmbService = new javax.swing.JComboBox<>();
        cmbDescription = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtPrix = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(55, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("IMPRIMER FACTURE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(222, 222, 222))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("INFOS PATIENT");

        jLabel3.setText("IdPatient");

        jLabel4.setText("Date Facture");

        jLabel5.setText("Facture N° ");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("DETAILS");

        jLabel7.setText("Service");

        jLabel8.setText("Description");

        cmbService.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Consultation générale", "Analyse Sanguine", "Injection" }));

        cmbDescription.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Examen complet", "Prise de sang", "Injection vacinale" }));

        jLabel9.setText("Prix");

        jLabel10.setText("Total");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Merci Pour Votre Confiance");

        jButton1.setBackground(new java.awt.Color(55, 204, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Fermer");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setBackground(new java.awt.Color(55, 204, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("Imprimer");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(287, 287, 287)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButton2))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtIdPatient, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                            .addComponent(txtDateFacture)
                                            .addComponent(txtNumero))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(141, 141, 141)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(8, 8, 8)
                                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(46, 46, 46))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(37, 37, 37)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtPrix)
                                            .addComponent(cmbDescription, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cmbService, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 46, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(21, 21, 21))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cmbService, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtIdPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(txtDateFacture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addComponent(cmbDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
        // ── 1. Chemin du PDF généré ──────────────────────────────
        String cheminPdf = System.getProperty("user.home") + "/facture_"
                + txtNumero.getText().trim() + ".pdf";
 
        // ── 2. Création du document PDF ──────────────────────────
        Document doc = new Document(PageSize.A4, 40, 40, 40, 40);
        PdfWriter.getInstance(doc, new FileOutputStream(cheminPdf));
        doc.open();
 
        // ── Couleurs ─────────────────────────────────────────────
        BaseColor bleu      = new BaseColor(14, 165, 233);   // #0ea5e9
        BaseColor bleuFonce = new BaseColor(2, 132, 199);
        BaseColor gris      = new BaseColor(248, 249, 250);
        BaseColor grisBord  = new BaseColor(220, 220, 220);
        BaseColor vert      = new BaseColor(220, 252, 231);
        BaseColor vertTexte = new BaseColor(22, 101, 52);
        BaseColor blanc     = BaseColor.WHITE;
        BaseColor noir      = BaseColor.BLACK;
        BaseColor grisTexte = new BaseColor(100, 100, 100);
 
        // ── Polices ───────────────────────────────────────────────
        Font fontTitre    = new Font(Font.FontFamily.HELVETICA, 20, Font.BOLD,   blanc);
        Font fontSousTitre= new Font(Font.FontFamily.HELVETICA, 10, Font.NORMAL, new BaseColor(220,240,255));
        Font fontFacture  = new Font(Font.FontFamily.HELVETICA, 22, Font.BOLD,   blanc);
        Font fontNumero   = new Font(Font.FontFamily.HELVETICA, 10, Font.NORMAL, new BaseColor(220,240,255));
        Font fontLabel    = new Font(Font.FontFamily.HELVETICA, 9,  Font.BOLD,   grisTexte);
        Font fontValeur   = new Font(Font.FontFamily.HELVETICA, 11, Font.BOLD,   noir);
        Font fontValeur2  = new Font(Font.FontFamily.HELVETICA, 10, Font.NORMAL, grisTexte);
        Font fontEntete   = new Font(Font.FontFamily.HELVETICA, 9,  Font.BOLD,   grisTexte);
        Font fontCell     = new Font(Font.FontFamily.HELVETICA, 10, Font.NORMAL, noir);
        Font fontTotal    = new Font(Font.FontFamily.HELVETICA, 13, Font.BOLD,   bleu);
        Font fontMerci    = new Font(Font.FontFamily.HELVETICA, 10, Font.ITALIC,  grisTexte);
        Font fontStatut   = new Font(Font.FontFamily.HELVETICA, 9,  Font.BOLD,   vertTexte);
 
        // ══════════════════════════════════════════════════════════
        // EN-TÊTE BLEUE
        // ══════════════════════════════════════════════════════════
        PdfPTable header = new PdfPTable(2);
        header.setWidthPercentage(100);
        header.setWidths(new float[]{1.5f, 1f});
        header.setSpacingAfter(16);
 
        // Colonne gauche : nom cabinet
        PdfPCell cellGauche = new PdfPCell();
        cellGauche.setBackgroundColor(bleu);
        cellGauche.setBorder(Rectangle.NO_BORDER);
        cellGauche.setPadding(16);
        Paragraph nomCabinet = new Paragraph("Cabinet Médical", fontTitre);
        nomCabinet.setSpacingAfter(3);
        cellGauche.addElement(nomCabinet);
        cellGauche.addElement(new Paragraph("Cotonou, Bénin — +229 00 00 00 00", fontSousTitre));
        header.addCell(cellGauche);
 
        // Colonne droite : FACTURE N°
        PdfPCell cellDroite = new PdfPCell();
        cellDroite.setBackgroundColor(bleuFonce);
        cellDroite.setBorder(Rectangle.NO_BORDER);
        cellDroite.setPadding(16);
        cellDroite.setHorizontalAlignment(Element.ALIGN_RIGHT);
        Paragraph titreFacture = new Paragraph("FACTURE", fontFacture);
        titreFacture.setAlignment(Element.ALIGN_RIGHT);
        titreFacture.setSpacingAfter(3);
        cellDroite.addElement(titreFacture);
        Paragraph numFacture = new Paragraph("N° " + txtNumero.getText().trim(), fontNumero);
        numFacture.setAlignment(Element.ALIGN_RIGHT);
        cellDroite.addElement(numFacture);
        header.addCell(cellDroite);
 
        doc.add(header);
 
        // ══════════════════════════════════════════════════════════
        // INFOS PATIENT + DÉTAILS FACTURE (2 colonnes)
        // ══════════════════════════════════════════════════════════
        PdfPTable infos = new PdfPTable(2);
        infos.setWidthPercentage(100);
        infos.setWidths(new float[]{1f, 1f});
        infos.setSpacingAfter(16);
 
        // Infos patient
        PdfPCell cellPatient = new PdfPCell();
        cellPatient.setBackgroundColor(gris);
        cellPatient.setBorderColor(grisBord);
        cellPatient.setBorderWidth(0.5f);
        cellPatient.setPadding(12);
        cellPatient.setPaddingRight(8);
        Paragraph labelPatient = new Paragraph("INFOS PATIENT", fontLabel);
        labelPatient.setSpacingAfter(6);
        cellPatient.addElement(labelPatient);
        cellPatient.addElement(new Paragraph(txtIdPatient.getText().trim(), fontValeur));
        cellPatient.addElement(new Paragraph("Date : " + txtDateFacture.getText().trim(), fontValeur2));
        infos.addCell(cellPatient);
 
        // Détails facture
        PdfPCell cellDetails = new PdfPCell();
        cellDetails.setBackgroundColor(gris);
        cellDetails.setBorderColor(grisBord);
        cellDetails.setBorderWidth(0.5f);
        cellDetails.setPadding(12);
        Paragraph labelDetails = new Paragraph("DÉTAILS FACTURE", fontLabel);
        labelDetails.setSpacingAfter(6);
        cellDetails.addElement(labelDetails);
        cellDetails.addElement(new Paragraph("Date : " + txtDateFacture.getText().trim(), fontValeur2));
        cellDetails.addElement(new Paragraph("Service : " + cmbService.getSelectedItem(), fontValeur2));
        cellDetails.addElement(new Paragraph("Description : " + cmbDescription.getSelectedItem(), fontValeur2));
        infos.addCell(cellDetails);
 
        doc.add(infos);
 
        // ══════════════════════════════════════════════════════════
        // TABLEAU DES SERVICES
        // ══════════════════════════════════════════════════════════
        PdfPTable tableau = new PdfPTable(3);
        tableau.setWidthPercentage(100);
        tableau.setWidths(new float[]{2f, 2.5f, 1.5f});
        tableau.setSpacingAfter(16);
 
        // En-têtes du tableau
        String[] entetes = {"Service", "Description", "Montant"};
        int[] alignEntetes = {Element.ALIGN_LEFT, Element.ALIGN_LEFT, Element.ALIGN_RIGHT};
        for (int i = 0; i < entetes.length; i++) {
            PdfPCell c = new PdfPCell(new Phrase(entetes[i], fontEntete));
            c.setBackgroundColor(gris);
            c.setBorderColor(grisBord);
            c.setBorderWidth(0.5f);
            c.setPadding(8);
            c.setHorizontalAlignment(alignEntetes[i]);
            tableau.addCell(c);
        }
 
        // Ligne de données
        String[] valeursGauche = {
            (String) cmbService.getSelectedItem(),
            (String) cmbDescription.getSelectedItem(),
            txtPrix.getText().trim() + " FCFA"
        };
        int[] alignValeurs = {Element.ALIGN_LEFT, Element.ALIGN_LEFT, Element.ALIGN_RIGHT};
        for (int i = 0; i < valeursGauche.length; i++) {
            PdfPCell c = new PdfPCell(new Phrase(valeursGauche[i], fontCell));
            c.setBorderColor(grisBord);
            c.setBorderWidth(0.5f);
            c.setPadding(8);
            c.setHorizontalAlignment(alignValeurs[i]);
            tableau.addCell(c);
        }
 
        doc.add(tableau);
 
        // ══════════════════════════════════════════════════════════
        // TOTAL
        // ══════════════════════════════════════════════════════════
        PdfPTable totalTable = new PdfPTable(2);
        totalTable.setWidthPercentage(40);
        totalTable.setHorizontalAlignment(Element.ALIGN_RIGHT);
        totalTable.setWidths(new float[]{1f, 1f});
        totalTable.setSpacingAfter(20);
 
        // Ligne Total
        PdfPCell cellTotalLabel = new PdfPCell(new Phrase("Total", fontTotal));
        cellTotalLabel.setBorder(Rectangle.TOP);
        cellTotalLabel.setBorderColor(grisBord);
        cellTotalLabel.setBorderWidth(0.5f);
        cellTotalLabel.setPadding(8);
        totalTable.addCell(cellTotalLabel);
 
        PdfPCell cellTotalVal = new PdfPCell(new Phrase(txtTotal.getText().trim() + " FCFA", fontTotal));
        cellTotalVal.setBorder(Rectangle.TOP);
        cellTotalVal.setBorderColor(grisBord);
        cellTotalVal.setBorderWidth(0.5f);
        cellTotalVal.setPadding(8);
        cellTotalVal.setHorizontalAlignment(Element.ALIGN_RIGHT);
        totalTable.addCell(cellTotalVal);
 
        doc.add(totalTable);
 
        // ══════════════════════════════════════════════════════════
        // PIED DE PAGE : statut + merci
        // ══════════════════════════════════════════════════════════
        PdfPTable pied = new PdfPTable(3);
        pied.setWidthPercentage(100);
        pied.setWidths(new float[]{1f, 2f, 1f});
 
        // Badge "Payé"
        PdfPCell cellStatut = new PdfPCell(new Phrase("  Payé  ", fontStatut));
        cellStatut.setBackgroundColor(vert);
        cellStatut.setBorderColor(new BaseColor(134, 239, 172));
        cellStatut.setBorderWidth(0.5f);
        cellStatut.setPadding(6);
        cellStatut.setHorizontalAlignment(Element.ALIGN_LEFT);
        pied.addCell(cellStatut);
 
        // Merci
        PdfPCell cellMerci = new PdfPCell(new Phrase("Merci pour votre confiance", fontMerci));
        cellMerci.setBorder(Rectangle.NO_BORDER);
        cellMerci.setHorizontalAlignment(Element.ALIGN_CENTER);
        cellMerci.setPadding(6);
        pied.addCell(cellMerci);
 
        // Mode paiement
        PdfPCell cellMode = new PdfPCell(new Phrase("Mode : Espèces", fontValeur2));
        cellMode.setBorder(Rectangle.NO_BORDER);
        cellMode.setHorizontalAlignment(Element.ALIGN_RIGHT);
        cellMode.setPadding(6);
        pied.addCell(cellMode);
 
        doc.add(pied);
        doc.close();
 
        // ── 3. Ouvrir + imprimer le PDF ──────────────────────────
        File fichierPdf = new File(cheminPdf);
        if (Desktop.isDesktopSupported()) {
            Desktop.getDesktop().open(fichierPdf); // ouvre le PDF
        }
 
        // Impression directe
        PrinterJob job = PrinterJob.getPrinterJob();
        if (job.printDialog()) {
            job.print();
            JOptionPane.showMessageDialog(this, "Impression réussie !");
        }
 
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
            "Erreur impression : " + e.getMessage(),
            "Erreur", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
         
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ImprimerJFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbDescription;
    private javax.swing.JComboBox<String> cmbService;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtDateFacture;
    private javax.swing.JTextField txtIdPatient;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtPrix;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
