/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;
import javax.swing.JOptionPane;

/**
 *
 * @author Idayath
 */
public class INSCRIPTIONJFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(INSCRIPTIONJFrame.class.getName());

    /**
     * Creates new form INSCRIPTIONJFrame
     */
    public INSCRIPTIONJFrame() {
        initComponents();
        remplirComboIndicatifs();
}

private java.util.List<entities.Pays> tousLesPays;

private void remplirComboIndicatifs() {
    tousLesPays = entities.Pays.listeComplete();

    javax.swing.DefaultComboBoxModel model = new javax.swing.DefaultComboBoxModel();
    for (entities.Pays p : tousLesPays) {
        model.addElement(p);
    }
    cbIndicatif.setModel(model);
    cbIndicatif.setRenderer(new PaysRenderer());
    cbIndicatif.setEditable(true);

    javax.swing.JTextField editeur = (javax.swing.JTextField) cbIndicatif.getEditor().getEditorComponent();

    editeur.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
        private boolean enCoursDeMiseAJour = false;

        @Override
        public void insertUpdate(javax.swing.event.DocumentEvent e) { filtrer(); }
        @Override
        public void removeUpdate(javax.swing.event.DocumentEvent e) { filtrer(); }
        @Override
        public void changedUpdate(javax.swing.event.DocumentEvent e) { }

        private void filtrer() {
            if (enCoursDeMiseAJour) return;
            javax.swing.SwingUtilities.invokeLater(() -> {
                enCoursDeMiseAJour = true;
                String texte = editeur.getText();
                String textePourRecherche = texte.toLowerCase();

                javax.swing.DefaultComboBoxModel filtre = new javax.swing.DefaultComboBoxModel();
                for (entities.Pays p : tousLesPays) {
                    if (textePourRecherche.isEmpty() || p.nom.toLowerCase().contains(textePourRecherche)) {
                        filtre.addElement(p);
                    }
                }
                cbIndicatif.setModel(filtre);
                editeur.setText(texte);

                if (!textePourRecherche.isEmpty() && filtre.getSize() > 0) {
                    cbIndicatif.showPopup();
                }
                enCoursDeMiseAJour = false;
            });
        }
    });
}
    
private static class PaysRenderer extends javax.swing.DefaultListCellRenderer {
    @Override
    public java.awt.Component getListCellRendererComponent(javax.swing.JList<?> list, Object value,
            int index, boolean isSelected, boolean cellHasFocus) {
        javax.swing.JLabel label = (javax.swing.JLabel) super.getListCellRendererComponent(
            list, value, index, isSelected, cellHasFocus);
        if (value instanceof entities.Pays) {
            entities.Pays p = (entities.Pays) value;
            java.net.URL url = getClass().getResource("/flags/" + p.code + ".png");
            if (url != null) {
                label.setIcon(new javax.swing.ImageIcon(url));
            }
            label.setText(p.toString());
        }
        return label;
    }
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbRole = new javax.swing.JComboBox<>();
        txtNom = new javax.swing.JTextField();
        txtPrenom = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtSpecialite = new javax.swing.JTextField();
        btnCreerCompte = new javax.swing.JButton();
        txtMotDePasse = new javax.swing.JPasswordField();
        txtConfirmerMotDePasse = new javax.swing.JPasswordField();
        cbIndicatif = new javax.swing.JComboBox<>();
        txtTelephone = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 255));

        jPanel1.setBackground(new java.awt.Color(55, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("SYSTEME DE GESTION DE CONSULTATIONS ET DE PAIEMENTS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Confirmer Mot de Passe");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Prenom");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Email");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Rôle");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Nom");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Mot de Passe");

        cbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Patient", "Medecin", "Sécrétaire", "Caissier", "Administrateur", " " }));

        txtNom.setText("jTextField1");
        txtNom.addActionListener(this::txtNomActionPerformed);

        txtPrenom.setText("jTextField2");

        txtEmail.setText("jTextField3");
        txtEmail.addActionListener(this::txtEmailActionPerformed);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Numéro de Téléphone");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Age ");

        txtAge.setText("jTextField6");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Spécialité");

        txtSpecialite.setText("jTextField8");

        btnCreerCompte.setBackground(new java.awt.Color(54, 204, 255));
        btnCreerCompte.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCreerCompte.setText("Créer le Compte");
        btnCreerCompte.addActionListener(this::btnCreerCompteActionPerformed);

        txtMotDePasse.setText("jPasswordField1");

        txtConfirmerMotDePasse.setText("jPasswordField1");

        cbIndicatif.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtTelephone.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(216, 216, 216)
                                .addComponent(btnCreerCompte, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbRole, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel10))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtMotDePasse, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(82, 82, 82)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cbIndicatif, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtTelephone))))
                                    .addComponent(txtConfirmerMotDePasse, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSpecialite, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtNom, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
                                            .addComponent(jLabel3)
                                            .addComponent(txtPrenom))))
                                .addGap(250, 250, 250)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(24, 24, 24)
                .addComponent(txtMotDePasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtConfirmerMotDePasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbIndicatif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(txtSpecialite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnCreerCompte)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void txtNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void btnCreerCompteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreerCompteActionPerformed
        // TODO add your handling code here:
    String role = (String) cbRole.getSelectedItem();
    String nom = txtNom.getText().trim();
    String prenom = txtPrenom.getText().trim();
    String email = txtEmail.getText().trim();
    String motDePasse = new String(txtMotDePasse.getPassword()).trim();
    String confirmMotDePasse = new String(txtConfirmerMotDePasse.getPassword()).trim();

    if (nom.isEmpty() || email.isEmpty() || motDePasse.isEmpty()) {
        JOptionPane.showMessageDialog(this,
            "Veuillez remplir au minimum le nom, l'email et le mot de passe.",
            "Erreur", JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (!motDePasse.equals(confirmMotDePasse)) {
        JOptionPane.showMessageDialog(this,
            "Les mots de passe ne correspondent pas.",
            "Erreur", JOptionPane.ERROR_MESSAGE);
        return;
    }

    if ("Patient".equals(role)) {
        controllers.PatientJpaController ctrl = new controllers.PatientJpaController();
        if (ctrl.trouverParEmail(email) != null) {
            JOptionPane.showMessageDialog(this, "Cet email est déjà utilisé.", "Erreur", JOptionPane.ERROR_MESSAGE);
            return;
        }
        entities.Patient p = new entities.Patient();
        p.setIdPatient(genererProchainId(ctrl.listerTous().size(), "P"));
        p.setNomPatient(nom);
        p.setPrenomPatient(prenom);
        p.setEmailPatient(email);
        p.setMotDePasse(motDePasse);
        try {
            p.setAge(Integer.parseInt(txtAge.getText().trim()));
        } catch (NumberFormatException e) {
            p.setAge(0);
        }
      Object selection = cbIndicatif.getSelectedItem();
        if (!(selection instanceof entities.Pays)) {
           JOptionPane.showMessageDialog(this,
           "Veuillez sélectionner un pays dans la liste déroulante.",
          "Erreur", JOptionPane.ERROR_MESSAGE);
        return;
      }
entities.Pays paysChoisi = (entities.Pays) selection;
      String telephoneComplet = "+" + paysChoisi.indicatif + " " + txtTelephone.getText().trim();
      p.setTelephone(telephoneComplet);

        if (ctrl.inserer(p)) {
            JOptionPane.showMessageDialog(this, "Compte patient créé avec succès ! Identifiant : " + p.getIdPatient());
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Erreur lors de la création du compte.", "Erreur", JOptionPane.ERROR_MESSAGE);
        }

    } else if ("Médecin".equals(role)) {
        controllers.MedecinJpaController ctrl = new controllers.MedecinJpaController();
        if (ctrl.trouverParEmail(email) != null) {
            JOptionPane.showMessageDialog(this, "Cet email est déjà utilisé.", "Erreur", JOptionPane.ERROR_MESSAGE);
            return;
        }
        entities.Medecin m = new entities.Medecin();
        m.setIdMedecin(genererProchainId(ctrl.listerTous().size(), "M"));
        m.setNomMedecin(nom);
        m.setPrenomMedecin(prenom);
        m.setEmailMedecin(email);
        m.setMotDePasse(motDePasse);
        m.setSpecialite(txtSpecialite.getText().trim());

        if (ctrl.inserer(m)) {
            JOptionPane.showMessageDialog(this, "Compte médecin créé avec succès ! Identifiant : " + m.getIdMedecin());
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Erreur lors de la création du compte.", "Erreur", JOptionPane.ERROR_MESSAGE);
        }

    } else if ("Secrétaire".equals(role) || "Caissier".equals(role) || "Administrateur".equals(role)) {
    controllers.PersonnelJpaController ctrl = new controllers.PersonnelJpaController();
    if (ctrl.trouverParEmail(email) != null) {
        JOptionPane.showMessageDialog(this, "Cet email est déjà utilisé.", "Erreur", JOptionPane.ERROR_MESSAGE);
        return;
    }
    entities.Personnel per = new entities.Personnel();
    per.setIdPersonnel(genererProchainId(ctrl.listerTous().size(), "E"));
    per.setNomPersonnel(nom);
    per.setEmailPersonnel(email);
    per.setMotDePasse(motDePasse);
    per.setRole(role);

    if (ctrl.inserer(per)) {
        JOptionPane.showMessageDialog(this, "Compte " + role + " créé avec succès ! Identifiant : " + per.getIdPersonnel());
        dispose();
    } else {
        JOptionPane.showMessageDialog(this, "Erreur lors de la création du compte.", "Erreur", JOptionPane.ERROR_MESSAGE);
    }
}
    }
// ── Génère le prochain identifiant (ex: P007, M010, E003) ──
    private String genererProchainId(int nombreExistant, String prefixe) {
    int prochain = nombreExistant + 1;
    return String.format("%s%03d", prefixe, prochain);

    }//GEN-LAST:event_btnCreerCompteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new INSCRIPTIONJFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreerCompte;
    private javax.swing.JComboBox<String> cbIndicatif;
    private javax.swing.JComboBox<String> cbRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAge;
    private javax.swing.JPasswordField txtConfirmerMotDePasse;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtMotDePasse;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtPrenom;
    private javax.swing.JTextField txtSpecialite;
    private javax.swing.JTextField txtTelephone;
    // End of variables declaration//GEN-END:variables
}
